Repository APPS-sookmyung/2023-POCHAK-server, pull requests merged in 2023-08, with the labels that each got.

#10 [fix/8-infra] user pk, sk 변경, api 설계 변경
  pochak/src/main/java/com/apps/pochak/alarm/controller/AlarmController.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/AlarmId.java
  pochak/src/main/java/com/apps/pochak/alarm/dto/CommentAlarmRequestDto.java
  pochak/src/main/java/com/apps/pochak/comment/controller/CommentController.java
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserController.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/domain/UserId.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
Labels: 🔨 fix, 🧩 infra, 🐰 sprint #1

#11 [fix/3-getFollowings] 팔로잉 리스트 조회 로직 수정
  pochak/src/main/java/com/apps/pochak/common/BaseResponse.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserController.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserFollowersResDto.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserFollowingsResDto.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
Labels: 🔨 fix, 🐰 sprint #1

#12 [feat/3-updateProfile] 프로필 수정하기
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserController.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserUpdateRequestDto.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserUpdateResDto.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
Labels: 💫feature, 🐰 sprint #1

#14 [feature/6-postupload] 포스트 업로드
  .idea/workspace.xml
  pochak/src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/PostRequestAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/dto/CommentAlarmRequestDto.java
  pochak/src/main/java/com/apps/pochak/comment/domain/Comment.java
  pochak/src/main/java/com/apps/pochak/comment/dto/ChildCommentDto.java
  pochak/src/main/java/com/apps/pochak/comment/dto/CommentResDto.java
  pochak/src/main/java/com/apps/pochak/comment/dto/ParentCommentDto.java
  pochak/src/main/java/com/apps/pochak/comment/repository/CommentCrudRepository.java
  pochak/src/main/java/com/apps/pochak/comment/repository/CommentRepository.java
  pochak/src/main/java/com/apps/pochak/common/BaseEntity.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/post/domain/Post.java
  pochak/src/main/java/com/apps/pochak/post/domain/PostId.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostDetailResDto.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostUploadRequestDto.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostUploadResDto.java
  pochak/src/main/java/com/apps/pochak/post/repository/PostCrudRepository.java
  pochak/src/main/java/com/apps/pochak/post/repository/PostRepository.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserFollowersResDto.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
  pochak/src/main/resources/application.properties
Labels: 💫feature, 🔨 fix, 🐰 sprint #1

#18 [feature/3-getProfileTab] 프로필 조회하기 - 찍힌 게시물들
  pochak/src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  pochak/src/main/java/com/apps/pochak/comment/domain/Comment.java
  pochak/src/main/java/com/apps/pochak/common/BaseEntity.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/common/DynamoDBConfig.java
  pochak/src/main/java/com/apps/pochak/post/domain/Post.java
  pochak/src/main/java/com/apps/pochak/post/domain/PostId.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/java/com/apps/pochak/publish/domain/Publish.java
  pochak/src/main/java/com/apps/pochak/tag/domain/Tag.java
  pochak/src/main/java/com/apps/pochak/tag/repository/TagRepository.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserController.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserProfileController.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserProfileResDto.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
Labels: 💫feature, 🐰 sprint #1

#27 [feature/3-follow-user] 유저 팔로우
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserProfileController.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserProfileResDto.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
Labels: 💫feature, 🐰 sprint #1

#29 [Feature/21-deploytestbranch]
  .github/workflows/deploy.yml
  appspec.yml
  pochak/appspec.yml
  pochak/build.gradle
  pochak/build.gradle.kts
  pochak/gradlew
  pochak/scripts/start.sh
  pochak/scripts/stop.sh
Labels: 💫feature, 🧩 infra, 🐰 sprint #2

#32 [feature/6-postupload] Fix: #6 randomcomment null check 로직 추가
  pochak/src/main/java/com/apps/pochak/comment/domain/Comment.java
  pochak/src/main/java/com/apps/pochak/post/domain/Post.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostDetailResDto.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/resources/application.properties
Labels: 💫feature, 🐰 sprint #1

#31 [feature/13-likepost] 포스트 좋아요 누르기
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostLikeResDto.java
  pochak/src/main/java/com/apps/pochak/post/repository/PostRepository.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
Labels: 💫feature, 🐰 sprint #1

#33 [feature/7-googleLogin] 구글 로그인 + JWT
  pochak/.gitignore
  pochak/build.gradle
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/common/Constant.java
  pochak/src/main/java/com/apps/pochak/common/SecurityConfig.java
  pochak/src/main/java/com/apps/pochak/common/WebClientConfig.java
  pochak/src/main/java/com/apps/pochak/login/controller/OAuthController.java
  pochak/src/main/java/com/apps/pochak/login/dto/GoogleTokenResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/GoogleUserResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/OAuthResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/PostTokenResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/UserInfoRequest.java
  pochak/src/main/java/com/apps/pochak/login/jwt/JwtAuthorizationFilter.java
  pochak/src/main/java/com/apps/pochak/login/jwt/JwtHeaderUtil.java
  pochak/src/main/java/com/apps/pochak/login/jwt/JwtService.java
  pochak/src/main/java/com/apps/pochak/login/oauth/GoogleOAuthService.java
  pochak/src/main/java/com/apps/pochak/user/domain/SocialType.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserCrudRepository.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/resources/application.properties
Labels: 💫feature, 🐰 sprint #1

#36 [fix/30-user-profile-api] user api 테스트, 수정
  pochak/build.gradle
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/login/jwt/JwtService.java
  pochak/src/main/java/com/apps/pochak/post/repository/PostCrudRepository.java
  pochak/src/main/java/com/apps/pochak/post/repository/PostRepository.java
  pochak/src/main/java/com/apps/pochak/tag/repository/TagRepository.java
  pochak/src/main/java/com/apps/pochak/user/controller/UserProfileController.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserProfileResDto.java
  pochak/src/main/java/com/apps/pochak/user/dto/UserUpdateRequestDto.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserCrudRepository.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
  pochak/src/main/resources/application.properties
  pochak/src/main/resources/log4j2.xml
Labels: 🔨 fix, 🐰 sprint #2
