Repository APPS-sookmyung/2023-POCHAK-server, pull requests merged in 2023-11, with the labels that each got.

#46 [feature/24-appleLogin] 애플 로그인
  pochak/.gitignore
  pochak/build.gradle
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/common/Constant.java
  pochak/src/main/java/com/apps/pochak/login/controller/OAuthController.java
  pochak/src/main/java/com/apps/pochak/login/dto/ApplePublicKeyResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/AppleTokenResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/GoogleTokenResponse.java
  pochak/src/main/java/com/apps/pochak/login/dto/UserInfoRequest.java
  pochak/src/main/java/com/apps/pochak/login/jwt/JwtHeaderUtil.java
  pochak/src/main/java/com/apps/pochak/login/oauth/AppleOAuthService.java
  pochak/src/main/java/com/apps/pochak/login/oauth/GoogleOAuthService.java
  pochak/src/main/java/com/apps/pochak/login/oauth/OAuthService.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserCrudRepository.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
Labels: 💫feature, 🐰 sprint #2

#52 [feature/20-find-all-alarms] public alarm 전체 조회
  pochak/src/main/java/com/apps/pochak/alarm/controller/AlarmController.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/PostRequestAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/dto/CommentAlarmRequestDto.java
  pochak/src/main/java/com/apps/pochak/alarm/dto/PublicAlarmsResDto.java
  pochak/src/main/java/com/apps/pochak/alarm/repository/AlarmCrudRepository.java
  pochak/src/main/java/com/apps/pochak/alarm/repository/AlarmRepository.java
  pochak/src/main/java/com/apps/pochak/alarm/service/AlarmService.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
Labels: 💫feature, 🔨 fix, 🧩 infra, 🐰 sprint #2

#57 [feature/23-s3ImageUpload] S3 이미지 업로드 작업
  pochak/build.gradle
  pochak/src/main/java/com/apps/pochak/common/AwsS3Config.java
  pochak/src/main/java/com/apps/pochak/common/AwsS3Service.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/common/config/DynamoDBConfig.java
  pochak/src/main/java/com/apps/pochak/login/controller/OAuthController.java
  pochak/src/main/java/com/apps/pochak/login/dto/UserInfoRequest.java
  pochak/src/main/java/com/apps/pochak/login/oauth/OAuthService.java
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostUploadRequestDto.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/resources/application.properties
Labels: 💫feature, 🐰 sprint #2

#59 [fix/53-delete-post] 게시글 삭제 API 상태 확인
  pochak/build.gradle
  pochak/src/main/java/com/apps/pochak/PochakApplication.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/PostRequestAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/repository/AlarmRepository.java
  pochak/src/main/java/com/apps/pochak/comment/domain/Comment.java
  pochak/src/main/java/com/apps/pochak/comment/dto/CommentUploadRequestDto.java
  pochak/src/main/java/com/apps/pochak/comment/repository/CommentRepository.java
  pochak/src/main/java/com/apps/pochak/comment/service/CommentService.java
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/java/com/apps/pochak/publish/repository/PublishRepository.java
  pochak/src/main/java/com/apps/pochak/tag/repository/TagRepository.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
  pochak/src/main/resources/static/APPS_LOGO.PNG
  pochak/src/test/java/com/apps/pochak/common/TestDataFactory.java
Labels: 🔨 fix

#63 [fix/55-manage-status] 초기 상태 확인 중
  pochak/src/main/java/com/apps/pochak/comment/service/CommentService.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/post/dto/LikedUsersResDto.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
Labels: 🐜 bug, 🔨 fix

#64 5차 배포
  pochak/build.gradle
  pochak/src/main/java/com/apps/pochak/PochakApplication.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/domain/PostRequestAlarm.java
  pochak/src/main/java/com/apps/pochak/alarm/repository/AlarmRepository.java
  pochak/src/main/java/com/apps/pochak/comment/domain/Comment.java
  pochak/src/main/java/com/apps/pochak/comment/dto/CommentUploadRequestDto.java
  pochak/src/main/java/com/apps/pochak/comment/repository/CommentRepository.java
  pochak/src/main/java/com/apps/pochak/comment/service/CommentService.java
  pochak/src/main/java/com/apps/pochak/common/AwsS3Config.java
  pochak/src/main/java/com/apps/pochak/common/AwsS3Service.java
  pochak/src/main/java/com/apps/pochak/common/BaseResponseStatus.java
  pochak/src/main/java/com/apps/pochak/common/config/DynamoDBConfig.java
  pochak/src/main/java/com/apps/pochak/login/controller/OAuthController.java
  pochak/src/main/java/com/apps/pochak/login/dto/UserInfoRequest.java
  pochak/src/main/java/com/apps/pochak/login/oauth/OAuthService.java
  pochak/src/main/java/com/apps/pochak/post/controller/PostController.java
  pochak/src/main/java/com/apps/pochak/post/dto/LikedUsersResDto.java
  pochak/src/main/java/com/apps/pochak/post/dto/PostUploadRequestDto.java
  pochak/src/main/java/com/apps/pochak/post/service/PostService.java
  pochak/src/main/java/com/apps/pochak/publish/repository/PublishRepository.java
  pochak/src/main/java/com/apps/pochak/tag/repository/TagRepository.java
  pochak/src/main/java/com/apps/pochak/user/domain/User.java
  pochak/src/main/java/com/apps/pochak/user/repository/UserRepository.java
  pochak/src/main/java/com/apps/pochak/user/service/UserService.java
  pochak/src/main/resources/application.properties
  pochak/src/main/resources/static/APPS_LOGO.PNG
  pochak/src/test/java/com/apps/pochak/common/TestDataFactory.java
Labels: 🖥️ distribution
